trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/*

pool:
  name: Agent pool

variables:
  awsServiceConnection: 'AWS_Access_Key'
  awsRegion: 'ap-south-1'
  terraformDirectory: '$(System.DefaultWorkingDirectory)/terraform'
  terraformStateBucket: "bucket-for-speedtest"
  terraformStateKey: "terraform/terraform.tfstate"

stages:
- stage: TerraformDeploy
  displayName: 'Terraform Plan & Apply'
  jobs:
  - job: DeployInfra
    displayName: 'Provision Infrastructure'
    steps:
    - checkout: self

    # Step 1: Configure AWS CLI using the Service Connection (secure & recommended)
#    - task: UseAWSCLI@1
#      displayName: 'Configure AWS CLI Credentials'
#      inputs:
#        awsCredentials: '$(awsServiceConnection)' # References the Service Connection
#        regionName: '$(awsRegion)'

    # Step 2: Install Terraform (if not pre-installed on your self-hosted agent)
    # Use the official TerraformInstaller task. It handles installation gracefully.
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest' # Or a specific version, e.g., '1.5.0'

    # Navigate to the directory containing your Terraform files
    - script: |
        echo "Navigating to Terraform directory: $(terraformDirectory)"
        cd $(terraformDirectory)
        
        # Step 3: Initialize Terraform
        # Terraform will automatically detect the S3 backend configured in your main.tf
        # and manage state locking with DynamoDB if configured.
        echo "--- Initializing Terraform ---"
        terraform init -upgrade # -upgrade ensures provider plugins are updated if needed
      displayName: 'Terraform Init'
      workingDirectory: '$(terraformDirectory)' # Ensure commands run in the right place

    # Step 4: Generate Terraform Plan
    - script: |
        echo "--- Generating Terraform Plan ---"
        # -out=tfplan.out saves the plan to a file.
        # This plan can then be used by 'terraform apply' to ensure consistency.
        terraform plan -out=tfplan.out
      displayName: 'Terraform Plan'
      workingDirectory: '$(terraformDirectory)'

    # Step 5: Apply Terraform Changes
    # You might want to split Plan and Apply into separate stages with an approval gate in between
    # for production environments. For now, they are in the same job for simplicity.
    - script: |
        echo "--- Applying Terraform Changes ---"
        # -auto-approve is used for automated deployments.
        # For production, consider using Azure DevOps Environments with approval gates.
        terraform apply -auto-approve tfplan.out
      displayName: 'Terraform Apply'
      workingDirectory: '$(terraformDirectory)'

- stage: TerraformDestroy
  displayName: 'Terraform Destroy'
  # Condition to run this stage:
  # This stage runs only if the 'DestroyResources' variable is explicitly set to 'true' when queuing the pipeline.
  # This provides a manual control mechanism for destructive operations.
  condition: |
    and(succeeded(), eq(variables['DestroyResources'], 'true'))
  
  jobs:
  - job: DestroyInfra
    displayName: 'Destroy Infrastructure'
    steps:
    - checkout: self

    # Step 1: Configure AWS CLI (essential for destroy as well)
#    - task: UseAWSCLI@1
#      displayName: 'Configure AWS CLI Credentials'
#      inputs:
#        awsCredentials: '$(awsServiceConnection)'
#        regionName: '$(awsRegion)'

    # Step 2: Install Terraform
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    # Navigate to the directory containing your Terraform files
    - script: |
        echo "Navigating to Terraform directory: $(terraformDirectory)"
        cd $(terraformDirectory)
        
        # Step 3: Initialize Terraform (must initialize to read state from S3 backend)
        echo "--- Initializing Terraform for Destroy ---"
        terraform init -upgrade
      displayName: 'Terraform Init for Destroy'
      workingDirectory: '$(terraformDirectory)'

    # Step 4: Generate Terraform Destroy Plan (Optional but Recommended)
    # This shows what will be destroyed before actually doing it.
    - script: |
        echo "--- Generating Terraform Destroy Plan ---"
        terraform plan -destroy -out=tfdestroy.out
      displayName: 'Terraform Destroy Plan'
      workingDirectory: '$(terraformDirectory)'

    # Step 5: Apply Terraform Destroy
    # Use -auto-approve for automation. For production, add approval gates.
    - script: |
        echo "--- Applying Terraform Destroy ---"
        terraform apply -destroy -auto-approve tfdestroy.out
      displayName: 'Terraform Destroy'
      workingDirectory: '$(terraformDirectory)'