# azure_pipelines_app.yml

name: AppPipeline_$(Date:yyyyMMdd)$(Rev:rr)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - app/*

pool:
  name: 'Agent pool'  

variables:
  DockerConnection: 'DockerHubConnection'
  awsRegion: 'ap-south-1'   
  appDirectory: '$(System.DefaultWorkingDirectory)/app'
  terraformDirectory: '$(System.DefaultWorkingDirectory)/terraform'
  terraformStateBucket: "bucket-for-speedtest"
  terraformStateKey: "terraform/terraform.tfstate"
  Docker_repo: 'gokulmohanraj/speed_test_app'
  Build_tag: $(Build.BuildId)

stages:
- stage: DockerBuild
  displayName: 'Docker Build Stage'
  jobs:  
  - job: BuildDockerImage
    displayName: 'Build Docker Image'
    steps:
    - script: |
        echo "Building Docker image..."
      displayName: 'Preparation step'
    - task: Docker@2
      inputs:
        containerRegistry: '$(DockerConnection)'
        repository: '$(Docker_repo)'
        command: 'buildAndPush'
        Dockerfile: '$(appDirectory)/Dockerfile'
        tags: |
          latest
          $(Build_tag)
      displayName: 'Docker Build'


