apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - name: speedtest
        image: gokulmohanraj/speed_test_app:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: speedtest
spec:
  selector:
    app: speedtest
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001

